// ReactJS/profile-manager-react/src/components/Card.jsx
import { NavLink } from "react-router-dom";
import PropTypes from 'prop-types';

function Card(props) {
    let profile = props.user;

    return (
        <div className="well well-sm" >
            <div className="row">
                <div className="col-md-4">
                    <img src={setImage(profile.photo, profile.sex)} alt={profile.name}
                        className="img-rounded img-responsive image-size" />
                </div>
                <div className="col-md-8">
                    <h4 >{profile.name}
                    </h4>
                    <small>{profile.city}, {profile.country} </small>
                    <p>
                        {profile.email}
                        <br />
                        {new Date(profile.birthdate).toLocaleDateString()}
                    </p>
                    <p>
                        <NavLink to={'profiles/edit/' + profile.id} className="btn btn-sm btn-success" >Edit</NavLink>
                    </p>
                </div>
            </div>
        </div>
    )
}

Card.propTypes = {
    user: PropTypes.shape({
        id: PropTypes.number,
        createdTs: PropTypes.string,
        updatedTs: PropTypes.string,
        name: PropTypes.string.isRequired,
        email: PropTypes.string.isRequired,
        sex: PropTypes.string.isRequired,
        birthdate: PropTypes.string.isRequired,
        phonenumber: PropTypes.string.isRequired,
        address: PropTypes.string,
        city: PropTypes.string,
        country: PropTypes.string,
        photo: PropTypes.string,
        favorite: PropTypes.bool
    })
}

function setImage(url, sex) {
    if (url) return url;
    else
        if (sex === "M") return "/images/male.jpg";
        else return "/images/female.jpg";

}

export default Card;

// Angular_11/profile-manager-angular/src/app/components/card/card.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { IProfile } from 'src/app/models/IProfile';
import { ProfileService } from 'src/app/services/profile.service';

@Component({
    selector: 'card',
    templateUrl: './card.component.html',
    styleUrls: ['./card.component.css']
})
export class CardComponent implements OnInit, OnChanges {

    @Input() profile: IProfile;

    constructor(private svc: ProfileService) {
        //console.log("Ctor: Value of profile is ", this.profile);
    }
    
    ngOnChanges(changes: SimpleChanges): void {
        //console.log("Card onchanges:", changes)
    }

    ngOnInit(): void {
        //console.log("OnInit: Value of profile is ", this.profile);
    }

}

<div class="well well-sm " [highlight]="'lightyellow'" >
    <div class="row">
        <div class="col-md-4">
            <img src="{{ profile.photo | image:profile.sex}}" alt="{{profile.name}}"
                class="img-rounded img-responsive image-size" />
        </div>
        <div class="col-md-8">
            <h4>{{ profile.name | uppercase }}
            </h4>
            <small>{{ profile.city }}, {{ profile.country }} </small>
            <p>
                {{ profile.email | lowercase }}
                <br />
                {{ profile.birthdate|date:'dd-MMM-yyyy'}}
            </p>    
            <p>
                <a [routerLink]="['profiles','edit', profile.id]" class="btn btn-sm btn-success" i18n="Edit link text|Link text for edit hyperlink">Edit</a>
            </p>                        
        </div>
    </div>
</div>
