// Angular_11/profile-manager-angular/src/app/components/add-profile/add-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ProfileService } from 'src/app/services/profile.service';

@Component({
    selector: 'add-profile',
    templateUrl: './add-profile.component.html',
    styleUrls: ['./add-profile.component.css']
})
export class AddProfileComponent implements OnInit {

    frm: FormGroup;

    constructor(private svc:ProfileService, 
        private router:Router) {
        this.frm = new FormGroup({
            name: new FormControl("", Validators.compose([Validators.required, Validators.minLength(3)])),
            email: new FormControl("", Validators.compose([Validators.required, Validators.email])),
            sex: new FormControl("M", Validators.required),
            birthdate: new FormControl("", Validators.required),
            phonenumber: new FormControl("", Validators.required),
            address: new FormControl("", Validators.required),
            city: new FormControl("", Validators.required),
            country: new FormControl("India", Validators.required),
            photo: new FormControl(""),
        })
    }

    public get Name(): AbstractControl {
        return this.frm.controls['name'];
    }

    public get Email(): AbstractControl {
        return this.frm.controls['email'];
    }

    public get Sex(): AbstractControl {
        return this.frm.controls['sex'];
    }

    public get BirthDate(): AbstractControl {
        return this.frm.controls['birthdate'];
    }

    public get Phone(): AbstractControl {
        return this.frm.controls['phonenumber'];
    }

    public get Address(): AbstractControl {
        return this.frm.controls['address'];
    }

    public get City(): AbstractControl {
        return this.frm.controls['city'];
    }

    public get Country(): AbstractControl {
        return this.frm.controls['country'];
    }

    public get Photo(): AbstractControl {
        return this.frm.controls['photo'];
    }

    public get Dirty():boolean{
        return this.frm.dirty;
    }

    ngOnInit(): void {
    }

    save(){
        if(this.frm.valid){
            this.svc.addProfile(this.frm.value)
            .subscribe(
                res=>{
                    alert("Added ");
                    this.router.navigate(['/'])
                },
                err=>alert("Failed to add profile")
            );
            
        }else{
            alert("Invalid form data, some validation error exists");
        }
    }

}

<div class="row">
    <div class="col-md-6 mx-auto">
        <h2 i18n="Page Header|Header of the Create profile page">Create Profile</h2>

        <form [formGroup]="frm" (ngSubmit)="save()" >
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text| Label text for name control">Name</label>
                    <input type="text"  formControlName="name" class="form-control" name="name"/>
                    <div *ngIf="Name.errors && Name.touched">
                        <div class="text-danger" *ngIf="Name.errors.required" i18n="Validation error|Required validation error message">Name cannot be empty</div>
                        <div class="text-danger" *ngIf="Name.errors.minlength" i18n="Validation error|Minlength validation error message">Minimum 3 characters required</div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for email control">Email</label>
                    <input type="email"  formControlName="email" name="email" class="form-control"  />
                    <div *ngIf="Email.errors && Email.touched">
                        <div class="text-danger" *ngIf="Email.errors.required" i18n="Validation error|Required validation error message">Email cannot be empty</div>
                        <div class="text-danger" *ngIf="Email.errors.email" i18n="Validation error|Email format validation error message">Invalid email format</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for photo control">Photo</label>
                    <input type="text" formControlName="photo" class="form-control" name="photo" />
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for sex control">Sex</label>
                    <select name="sex" formControlName="sex" class="form-control" id="">
                        <option value="M">Male</option>
                        <option value="F">Female</option>
                    </select>
                    <div *ngIf="Sex.errors && Sex.touched">
                        <div class="text-danger" *ngIf="Sex.errors.required" i18n="Validation error|Required validation error message">Sex cannot be empty</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for birthdate control">Birthday</label>                                
                    <input type="date" formControlName="birthdate" name="birthdate" class="form-control" />
                    <div *ngIf="BirthDate.errors && BirthDate.touched">
                        <div class="text-danger" *ngIf="BirthDate.errors.required" i18n="Validation error|Required validation error message">Birth date cannot be empty</div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for phonenumber control">Phone</label>
                    <input type="tel" formControlName="phonenumber" name="phonenumber" class="form-control" />
                    <div *ngIf="Phone.errors && Phone.touched">
                        <div class="text-danger" *ngIf="Phone.errors.required" i18n="Validation error|Required validation error message">Phone number cannot be empty</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for address control">Address</label>
                    <input type="text" formControlName="address"  name="address" class="form-control" />
                    <div *ngIf="Address.errors && Address.touched">
                        <div class="text-danger" *ngIf="Address.errors.required" i18n="Validation error|Required validation error message">Address cannot be empty</div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for city control">City</label>
                    <input type="text" formControlName="city" name="city" class="form-control" />
                    <div *ngIf="City.errors && City.touched">
                        <div class="text-danger" *ngIf="City.errors.required"  i18n="Validation error|Required validation error message">City cannot be empty</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for country control">Country</label>
                    <input type="text" formControlName="country" name="country" class="form-control" />
                    <div *ngIf="Country.errors && Country.touched">
                        <div class="text-danger" *ngIf="Country.errors.required" i18n="Validation error|Required validation error message">Country cannot be empty</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12 text-center">
                    <button type="submit" [disabled]="frm.invalid" class="btn btn-primary" i18n="Submit button text|Save button text for create profile form" >Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

// ReactJS/profile-manager-react/src/components/AddProfile.jsx
import React, { Component } from "react";

export default class AddProfileForm extends Component {

    constructor(props) {
        super(props);
        this.state = {
            profile: {
                name: "",
                email: "",
                sex: "M",
                birthdate: "",
                phonenumber: "",
                address: "",
                city: "",
                country: "",
                photo: ""
            },
            errors: {
                name: "",
                email: "",
                birthdate: "",
                phonenumber: "",
                country: ""
            }
        }
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event) {
        event.preventDefault();
        const { name, value } = event.target;
        let errors = this.state.errors;
        let profile = this.state.profile;
        switch (name) {
            case "name":
                if (!value || value.length === 0) errors.name = "Name cannot be empty";
                else if (value.length < 2) errors.name = "Minimum 2 characters required";
                else errors.name = "";
                break;
            case "email":
                //eslint-disable-next-line
                let pattern = RegExp(/^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i);
                if (!value || value.length === 0) errors.email = "Email cannot be empty";
                else if (!pattern.test(value)) errors.email = "Invalid email format";
                else errors.email = "";
                break;
            case "birthdate":
                if (!value || value.length === 0) errors.birthdate = "Birth date cannot be empty";
                else errors.birthdate = "";
                break;
            case "phonenumber":
                if (!value || value.length === 0) errors.phonenumber = "Phone number cannot be empty";
                else errors.phonenumber = "";
                break;
            case "city":
                if (!value || value.length === 0) errors.city = "City cannot be empty";
                else errors.city = "";
                break;
            case "address":
                if (!value || value.length === 0) errors.address = "Address cannot be empty";
                else errors.address = "";
                break;
            case "country":
                if (!value || value.length === 0) errors.country = "Country cannot be empty";
                else errors.country = "";
                break;
            default:
                break;
        }
        profile[name] = value;
        this.setState({ errors, profile }, () => {
            //console.log(this.state)
        });
    }

    handleSubmit(event) {
        event.preventDefault();
        if (!this.validateForm()) {
            alert("Invalid form");
        }
        else {
            this.props.addProfile(this.state.profile)
                .then(res => {
                    this.props.history.push('/');
                })
        }
    }
    render() {
        let errors = this.state.errors;
        return (
            <div className="row">
                <div className="col-md-6 mx-auto">
                    <h2>Create Profile</h2>
                    <form onSubmit={this.handleSubmit} >
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Name</label>
                                <input type="text" className="form-control" name="name" onChange={this.handleChange} />
                                {errors.name && <div className="text-danger">{errors.name}</div>}
                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Email</label>
                                <input type="email" name="email" className="form-control" onChange={this.handleChange} />
                                {errors.email && <div className="text-danger">{errors.email}</div>}
                            </div >
                        </div >
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Photo</label>
                                <input type="text" className="form-control" name="photo" onChange={this.handleChange} />

                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Sex</label>
                                <select name="sex" className="form-control" value={this.state.profile.sex} id="" onChange={this.handleChange}>
                                    <option value="M">Male</option>
                                    <option value="F">Female</option>
                                </select>
                            </div >
                        </div >
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Birthday</label>
                                <input type="date" name="birthdate" className="form-control" onChange={this.handleChange} />
                                {errors.birthdate && <div className="text-danger">{errors.birthdate}</div>}
                            </div >
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Phone</label>
                                <input type="tel" name="phonenumber" className="form-control" onChange={this.handleChange} />
                                {errors.phonenumber && <div className="text-danger">{errors.phonenumber}</div>}
                            </div >
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Address</label>
                                <input type="text" name="address" className="form-control" onChange={this.handleChange} />
                                {errors.address && <div className="text-danger">{errors.address}</div>}
                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">City</label>
                                <input type="text" name="city" className="form-control" onChange={this.handleChange} />
                                {errors.city && <div className="text-danger">{errors.city}</div>}
                            </div>
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Country</label>
                                <input type="text" name="country" className="form-control" onChange={this.handleChange} />
                                {errors.country && <div className="text-danger">{errors.country}</div>}
                            </div >
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-12 text-center">
                                <button type="submit" className="btn btn-primary" >Save</button>
                            </div>
                        </div >
                    </form >
                </div >
            </div >
        );
    }

    validateForm() {
        let profile = this.state.profile;
        let errors = this.state.errors;
        let valid = true;
        Object.keys(profile).forEach((field) => {
            let value = profile[field];
            switch (field) {
                case "name":
                    if (!value || value.length === 0) errors.name = "Name cannot be empty";
                    else if (value.length < 2) errors.name = "Minimum 2 characters required";
                    else errors.name = "";
                    break;
                case "email":
                    //eslint-disable-next-line
                    let pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
                    if (!value || value.length === 0) errors.email = "Email cannot be empty";
                    else if (!pattern.test(value)) errors.email = "Invalid email format";
                    else errors.email = "";
                    break;
                case "birthdate":
                    if (!value || value.length === 0) errors.birthdate = "Birth date cannot be empty";
                    else errors.birthdate = "";
                    break;
                case "phonenumber":
                    if (!value || value.length === 0) errors.phonenumber = "Phone number cannot be empty";
                    else errors.phonenumber = "";
                    break;
                case "city":
                    if (!value || value.length === 0) errors.city = "City cannot be empty";
                    else errors.city = "";
                    break;
                case "address":
                    if (!value || value.length === 0) errors.address = "Address cannot be empty";
                    else errors.address = "";
                    break;
                case "country":
                    if (!value || value.length === 0) errors.country = "Country cannot be empty";
                    else errors.country = "";
                    break;
                default:
                    break;
            }
        })
        this.setState({ errors, profile });

        Object.values(errors).forEach((val) => (val.length > 0) && (valid = false));
        return valid;
    }
}
