// Angular_11/profile-manager-angular/src/app/components/edit-profile/edit-profile.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { IProfile } from 'src/app/models/IProfile';
import { ProfileService } from 'src/app/services/profile.service';

@Component({
    selector: 'edit-profile',
    templateUrl: './edit-profile.component.html',
    styleUrls: ['./edit-profile.component.css']
})
export class EditProfileComponent implements OnInit {

    profile: IProfile;
    @ViewChild('frm') form: NgForm;

    constructor(private route: ActivatedRoute, private svc: ProfileService, private router: Router) {

        let data = this.route.snapshot.data["profile"];
        this.profile = {
            name: data.name,
            email: data.email,
            phonenumber: data.phonenumber,
            photo: data.photo,
            sex: data.sex,
            birthdate: data.birthdate,
            address: data.address,
            city: data.city,
            country: data.country
        }
    }

    public get Dirty(): boolean {
        return this.form.dirty;
    }

    ngOnInit(): void {
    }

    update(frm) {
        if (frm.valid) {
            this.svc.updateProfile(this.profile)
                .subscribe(
                    res => {
                        alert("Updated");
                        this.router.navigate(['/'])
                    },
                    err => alert("Failed to update")
                )
            alert("updated");
        } else {
            alert("Invalid data")
        }
    }

}

<div class="row">
    <div class="col-md-6 mx-auto">
        <h2>Update Profile</h2>
        <form #frm="ngForm" (ngSubmit)="update(frm)">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for name control">Name</label>
                    <input type="text" class="form-control" name="name" required minlength="3"
                        [(ngModel)]="profile.name" #name="ngModel" />
                    <div *ngIf="name.errors && name.touched" class="text-danger">
                        <div *ngIf="name.errors.required" i18n="Validation error|Required validation error message">Name cannot be empty</div>
                        <div *ngIf="name.errors.minlength" i18n="Validation error|Minlength validation error message">Minimum 3 characters required</div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for email control">Email</label>
                    <input type="email" name="email" class="form-control" required
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" [(ngModel)]="profile.email"
                        #email="ngModel" />
                        <div *ngIf="email.errors && email.touched">
                            <div class="text-danger" *ngIf="email.errors.required" i18n="Validation error|Required validation error message">Email cannot be empty</div>
                            <div class="text-danger" *ngIf="email.errors.pattern" i18n="Validation error|Email format validation error message">Invalid email format</div>
                        </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for photo control">Photo</label>
                    <input type="text" class="form-control" name="photo" [(ngModel)]="profile.photo" #photo="ngModel" />
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for sex control">Sex</label>
                    <select name="sex" class="form-control" id="" required [(ngModel)]="profile.sex" #sex="ngModel">
                        <option value="M">Male</option>
                        <option value="F">Female</option>
                    </select>
                    <div *ngIf="sex.errors && sex.touched">
                        <div class="text-danger" *ngIf="sex.errors.required" i18n="Validation error|Required validation error message">Sex cannot be empty</div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for birthdate control">Birthday</label>
                    <input type="date" name="birthdate" class="form-control" required 
                        [ngModel] ="profile.birthdate | date:'yyyy-MM-dd'" 
                        (ngModelChange)="profile.birthdate = $event"
                        #bdate="ngModel" />
                        <div *ngIf="bdate.errors && bdate.touched">
                            <div class="text-danger" *ngIf="bdate.errors.required" i18n="Validation error|Required validation error message">Birth date cannot be empty</div>
                        </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for phonenumber control">Phone</label>
                    <input type="tel" name="phonenumber" class="form-control" required [(ngModel)]="profile.phonenumber"
                        #phno="ngModel" />
                        <div *ngIf="phno.errors && phno.touched">
                            <div class="text-danger" *ngIf="phno.errors.required" i18n="Validation error|Required validation error message">Phone number cannot be empty</div>
                        </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for address control">Address</label>
                    <input type="text" name="address" class="form-control" required [(ngModel)]="profile.address"
                        #address="ngModel" />
                        <div *ngIf="address.errors && address.touched">
                            <div class="text-danger" *ngIf="address.errors.required" i18n="Validation error|Required validation error message">Address cannot be empty</div>
                        </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for city control">City</label>
                    <input type="text" name="city" class="form-control" required [(ngModel)]="profile.city"
                        #city="ngModel" />
                        <div *ngIf="city.errors && city.touched">
                            <div class="text-danger" *ngIf="city.errors.required" i18n="Validation error|Required validation error message">City cannot be empty</div>
                        </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 control-label" i18n="Control label text|Label text for country control">Country</label>
                    <input type="text" name="country" class="form-control" required [(ngModel)]="profile.country"
                        #country="ngModel" />
                        <div *ngIf="country.errors && country.touched">
                            <div class="text-danger" *ngIf="country.errors.required" i18n="Validation error|Required validation error message">Country cannot be empty</div>
                        </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12 text-center">
                    <button type="submit" [disabled]="frm.invalid" class="btn btn-primary" i18n="Submit button text|Save button text for update profile form">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

// ReactJS/profile-manager-react/src/components/EditProfile.jsx
import React, { Component } from "react";
import profiles from '../data/inmemory-data';
import { withRouter } from "react-router-dom";

class EditProfileForm extends Component {

    constructor(props) {
        super(props);
        let id = this.props.match.params.id;
        let data = profiles.find(p => p.id == id);
        this.state = {
            profile: data,
            errors: {
                name: "",
                email: "",
                phonenumber: "",
                birthdate: "",
                country: "",
                city: "",
                address: ""
            }
        }
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }


    handleChange(e) {
        e.preventDefault();
        const { name, value } = e.target; //ES6 object destructuring 
        //let  name = e.target.name; //ES5 manual assignment
        //let value= e.target.value; //ES5 

        //Update the state with form control values
        let profile = this.state.profile;
        profile[name] = value;

        //Error validations
        let errors = this.state.errors;
        switch (name) {
            case "name":
                if (!value || value.length === 0) errors.name = "Name cannot be empty";
                else if (value.length < 3) errors.name = "Minimum 3 characters required";
                else errors.name = "";
                break;
            case "email":
                //eslint-disable-next-line
                let pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
                if (!value || value.length === 0) errors.email = "Email cannot be empty";
                else if (!pattern.test(value)) errors.email = "Invalid email format";
                else errors.email = "";
                break;
            case "birthdate":
                if (!value || value.length === 0) errors.birthdate = "Birth date cannot be empty";
                else errors.birthdate = "";
                break;
            case "phonenumber":
                if (!value || value.length === 0) errors.phonenumber = "Phone number cannot be empty";
                else errors.phonenumber = "";
                break;
            case "city":
                if (!value || value.length === 0) errors.city = "City cannot be empty";
                else errors.city = "";
                break;
            case "address":
                if (!value || value.length === 0) errors.address = "Address cannot be empty";
                else errors.address = "";
                break;
            case "country":
                if (!value || value.length === 0) errors.country = "Country cannot be empty";
                else errors.country = "";
                break;
            default:
                break;
        }

        this.setState({ profile, errors });
    }

    handleSubmit(e) {
        e.preventDefault();
        if (this.validateForm()){
            alert("Valid");
            //console.log(this.props);
            this.props.history.push('/');
        }
        else
            alert("Invalid");
    }

    validateForm() {
        let profile = this.state.profile;
        let errors = this.state.errors;
        let valid = true;
        Object.keys(profile).forEach((field) => {
            let value = profile[field];
            switch (field) {
                case "name":
                    if (!value || value.length === 0) errors.name = "Name cannot be empty";
                    else if (value.length < 2) errors.name = "Minimum 2 characters required";
                    else errors.name = "";
                    break;
                case "email":
                    //eslint-disable-next-line
                    let pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
                    if (!value || value.length === 0) errors.email = "Email cannot be empty";
                    else if (!pattern.test(value)) errors.email = "Invalid email format";
                    else errors.email = "";
                    break;
                case "birthdate":
                    if (!value || value.length === 0) errors.birthdate = "Birth date cannot be empty";
                    else errors.birthdate = "";
                    break;
                case "phonenumber":
                    if (!value || value.length === 0) errors.phonenumber = "Phone number cannot be empty";
                    else errors.phonenumber = "";
                    break;
                case "city":
                    if (!value || value.length === 0) errors.city = "City cannot be empty";
                    else errors.city = "";
                    break;
                case "address":
                    if (!value || value.length === 0) errors.address = "Address cannot be empty";
                    else errors.address = "";
                    break;
                case "country":
                    if (!value || value.length === 0) errors.country = "Country cannot be empty";
                    else errors.country = "";
                    break;
                default:
                    break;
            }
        })
        this.setState({ errors, profile });

        Object.values(errors).forEach((val) => (val.length > 0) && (valid = false));
        return valid;
    }

    render() {
        let errors = this.state.errors;
        let profile = this.state.profile;

        return (
            <div className="row">
                <div className="col-md-6 mx-auto">
                    <h2>Update Profile</h2>
                    <form onSubmit={this.handleSubmit}>
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Name</label>
                                <input type="text" className="form-control" name="name" value={profile.name} onChange={this.handleChange} />
                                {errors.name.length > 0 && <div className="text-danger">{errors.name}</div>}
                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Email</label>
                                <input type="email" name="email" className="form-control" value={profile.email} onChange={this.handleChange} />
                                {errors.email.length > 0 && <div className="text-danger">{errors.email}</div>}
                            </div >
                        </div >
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Photo</label>
                                <input type="text" className="form-control" name="photo" value={profile.photo} onChange={this.handleChange} />

                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Sex</label>
                                <select name="sex" className="form-control" value={profile.sex} onChange={this.handleChange}>
                                    <option value="M">Male</option>
                                    <option value="F">Female</option>
                                </select>
                            </div >
                        </div >
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Birthday</label>
                                <input type="date" name="birthdate" className="form-control" value={profile.birthdate} onChange={this.handleChange} />
                                {errors.birthdate && <div className="text-danger">{errors.birthdate}</div>}
                            </div >
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Phone</label>
                                <input type="tel" name="phonenumber" className="form-control" value={profile.phonenumber} onChange={this.handleChange} />
                                {errors.phonenumber && <div className="text-danger">{errors.phonenumber}</div>}
                            </div >
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Address</label>
                                <input type="text" name="address" className="form-control" value={profile.address} onChange={this.handleChange} />
                                {errors.address && <div className="text-danger">{errors.address}</div>}
                            </div>
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">City</label>
                                <input type="text" name="city" className="form-control" value={profile.city} onChange={this.handleChange} />
                                {errors.city && <div className="text-danger">{errors.city}</div>}
                            </div>
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-6">
                                <label className="col-sm-2 control-label">Country</label>
                                <input type="text" name="country" value={profile.country} className="form-control" onChange={this.handleChange} />
                                {errors.country && <div className="text-danger">{errors.country}</div>}
                            </div >
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-12 text-center">
                                <button type="submit" className="btn btn-primary" >Update</button>
                            </div>
                        </div >
                    </form >
                </div >
            </div >
        );
    }

}

//Use the HOC to enable history property for navigation
export default withRouter(EditProfileForm);
